import type { Circle, Event, Organization, UserProfile } from "./types";

export const organizations: Organization[] = [
  {
    id: "company-nova",
    name: "NovaWorks",
    type: "employer",
    city: "New York",
    neighborhood: "NYC Office Hub",
    industry: "Technology",
    companySize: "201-500",
    workplaceModel: "Hybrid",
    officeLocations: ["New York", "Brooklyn", "Remote near hub"],
    status: "active",
    memberCount: 342,
  },
];

export const demoUsers: UserProfile[] = [
  {
    id: "u-farid",
    name: "Farid",
    email: "farid@novaworks.example",
    ageRange: "25-34",
    city: "New York",
    neighborhood: "NYC Office Hub",
    company: "NovaWorks",
    department: "Marketing",
    organizationId: "company-nova",
    organizationType: "employer",
    workMode: "hybrid",
    roleLevel: "individual_contributor",
    tenure: "one_to_three_years",
    interests: ["coffee", "startups", "design", "strategy"],
    socialGoals: ["cross_functional_colleagues", "feel_connected"],
    availability: ["weekday_lunch", "wednesday"],
    preferredFormats: ["coffee_chats", "lunch_circles"],
    vibes: ["casual", "professional"],
    photo: "https://i.pravatar.cc/150?img=13",
    onboardingCompleted: true,
  },
  {
    id: "u-1",
    name: "Maya Chen",
    email: "maya@novaworks.example",
    ageRange: "25-34",
    city: "New York",
    neighborhood: "NYC Office Hub",
    company: "NovaWorks",
    department: "Product",
    organizationId: "company-nova",
    organizationType: "employer",
    workMode: "hybrid",
    roleLevel: "individual_contributor",
    tenure: "new_hire",
    interests: ["coffee", "design", "walking", "language exchange"],
    socialGoals: ["new_hire_onboarding", "cross_functional_colleagues", "feel_connected"],
    availability: ["weekday_lunch", "weekday_evening", "wednesday"],
    preferredFormats: ["lunch_circles", "walk_and_talks"],
    vibes: ["casual", "food_centered", "culture_focused"],
    photo: "https://i.pravatar.cc/150?img=44",
    onboardingCompleted: true,
  },
  {
    id: "u-2",
    name: "Julian Brooks",
    email: "julian@novaworks.example",
    ageRange: "25-34",
    city: "New York",
    neighborhood: "NYC Office Hub",
    company: "NovaWorks",
    department: "Engineering",
    organizationId: "company-nova",
    organizationType: "employer",
    workMode: "hybrid",
    roleLevel: "individual_contributor",
    tenure: "three_to_twelve_months",
    interests: ["running", "coffee", "architecture", "career growth"],
    socialGoals: ["cross_functional_colleagues", "professional_peer_support"],
    availability: ["weekday_lunch", "weekday_afternoon", "wednesday"],
    preferredFormats: ["coffee_chats", "walk_and_talks"],
    vibes: ["professional", "active"],
    photo: "https://i.pravatar.cc/150?img=52",
    onboardingCompleted: true,
  },
  {
    id: "u-3",
    name: "Nora Patel",
    email: "nora@novaworks.example",
    ageRange: "25-34",
    city: "New York",
    neighborhood: "NYC Office Hub",
    company: "NovaWorks",
    department: "People",
    organizationId: "company-nova",
    organizationType: "employer",
    workMode: "mostly_in_office",
    roleLevel: "manager",
    tenure: "one_to_three_years",
    interests: ["books", "food", "mentorship", "museums"],
    socialGoals: ["manager_peer_support", "professional_peer_support", "feel_connected"],
    availability: ["weekday_lunch", "weekday_evening", "office_anchor_days"],
    preferredFormats: ["manager_peer_circles", "lunch_circles"],
    vibes: ["reflective", "career_focused"],
    managerStatus: true,
    photo: "https://i.pravatar.cc/150?img=5",
    onboardingCompleted: true,
  },
  {
    id: "u-4",
    name: "Ari Morgan",
    email: "ari@novaworks.example",
    ageRange: "25-34",
    city: "Brooklyn",
    neighborhood: "NYC Office Hub",
    company: "NovaWorks",
    department: "Marketing",
    organizationId: "company-nova",
    organizationType: "employer",
    workMode: "remote_near_hub",
    roleLevel: "individual_contributor",
    tenure: "three_to_twelve_months",
    interests: ["music", "food", "boxing", "coffee"],
    socialGoals: ["office_city_connection", "feel_connected"],
    availability: ["weekday_evening", "wednesday", "thursday"],
    preferredFormats: ["team_dinners", "coffee_chats"],
    vibes: ["food_centered", "casual"],
    photo: "https://i.pravatar.cc/150?img=59",
    onboardingCompleted: true,
  },
  {
    id: "u-5",
    name: "Sofia Rivera",
    email: "sofia@novaworks.example",
    ageRange: "25-34",
    city: "New York",
    neighborhood: "NYC Office Hub",
    company: "NovaWorks",
    department: "Design",
    organizationId: "company-nova",
    organizationType: "employer",
    workMode: "hybrid",
    roleLevel: "individual_contributor",
    tenure: "new_hire",
    interests: ["design", "ceramics", "coffee", "walking"],
    socialGoals: ["new_hire_onboarding", "cross_functional_colleagues"],
    availability: ["weekday_lunch", "wednesday", "friday"],
    preferredFormats: ["lunch_circles", "walk_and_talks"],
    vibes: ["casual", "culture_focused"],
    photo: "https://i.pravatar.cc/150?img=47",
    onboardingCompleted: true,
  },
  {
    id: "u-6",
    name: "Leo Grant",
    email: "leo@novaworks.example",
    ageRange: "25-34",
    city: "New York",
    neighborhood: "NYC Office Hub",
    company: "NovaWorks",
    department: "Data",
    organizationId: "company-nova",
    organizationType: "employer",
    workMode: "mostly_remote",
    roleLevel: "senior_manager",
    tenure: "three_plus_years",
    interests: ["running", "coffee", "books", "strategy"],
    socialGoals: ["professional_peer_support", "manager_peer_support"],
    availability: ["weekday_breakfast", "weekday_lunch", "office_anchor_days"],
    preferredFormats: ["coffee_chats", "manager_peer_circles"],
    vibes: ["professional", "reflective"],
    managerStatus: true,
    photo: "https://i.pravatar.cc/150?img=12",
    onboardingCompleted: true,
  },
  {
    id: "u-7",
    name: "Imani Okafor",
    email: "imani@novaworks.example",
    ageRange: "25-34",
    city: "New York",
    neighborhood: "NYC Office Hub",
    company: "NovaWorks",
    department: "Customer Success",
    organizationId: "company-nova",
    organizationType: "employer",
    workMode: "hybrid",
    roleLevel: "manager",
    tenure: "one_to_three_years",
    interests: ["food", "language exchange", "travel", "wellness"],
    socialGoals: ["erg_circle", "feel_connected", "cross_functional_colleagues"],
    availability: ["weekday_lunch", "weekday_evening", "thursday"],
    preferredFormats: ["erg_circles", "lunch_circles"],
    vibes: ["food_centered", "culture_focused"],
    ergInterests: ["Women at Nova", "Global Cultures"],
    managerStatus: true,
    photo: "https://i.pravatar.cc/150?img=38",
    onboardingCompleted: true,
  },
  {
    id: "u-8",
    name: "Theo Martin",
    email: "theo@novaworks.example",
    ageRange: "35-44",
    city: "New York",
    neighborhood: "NYC Office Hub",
    company: "NovaWorks",
    department: "Finance",
    organizationId: "company-nova",
    organizationType: "employer",
    workMode: "mostly_in_office",
    roleLevel: "director_plus",
    tenure: "three_plus_years",
    interests: ["architecture", "mentorship", "books", "walking"],
    socialGoals: ["manager_peer_support", "cross_functional_colleagues"],
    availability: ["weekday_lunch", "office_anchor_days", "wednesday"],
    preferredFormats: ["manager_peer_circles", "walk_and_talks"],
    vibes: ["professional", "reflective"],
    managerStatus: true,
    onboardingCompleted: true,
  },
  {
    id: "u-9",
    name: "Camila Santos",
    email: "camila@novaworks.example",
    ageRange: "25-34",
    city: "New York",
    neighborhood: "NYC Office Hub",
    company: "NovaWorks",
    department: "Sales",
    organizationId: "company-nova",
    organizationType: "employer",
    workMode: "hybrid",
    roleLevel: "individual_contributor",
    tenure: "new_hire",
    interests: ["startups", "coffee", "fitness", "dinners"],
    socialGoals: ["new_hire_onboarding", "professional_peer_support"],
    availability: ["weekday_lunch", "weekday_afternoon", "friday"],
    preferredFormats: ["lunch_circles", "skill_career_circles"],
    vibes: ["career_focused", "food_centered"],
    onboardingCompleted: true,
  },
  {
    id: "u-10",
    name: "Ben Adler",
    email: "ben@novaworks.example",
    ageRange: "25-34",
    city: "New York",
    neighborhood: "NYC Office Hub",
    company: "NovaWorks",
    department: "Operations",
    organizationId: "company-nova",
    organizationType: "employer",
    workMode: "hybrid",
    roleLevel: "individual_contributor",
    tenure: "three_to_twelve_months",
    interests: ["process design", "running", "coffee", "sports"],
    socialGoals: ["office_city_connection", "cross_functional_colleagues"],
    availability: ["weekday_breakfast", "weekday_lunch", "wednesday"],
    preferredFormats: ["coffee_chats", "walk_and_talks"],
    vibes: ["active", "professional"],
    onboardingCompleted: true,
  },
];

export const demoCircle: Circle = {
  id: "circle-1",
  organizationId: "company-nova",
  name: "Hybrid Wednesday Circle",
  theme: "Cross-team lunch and low-pressure workplace connection",
  programType: "Hybrid Office-Day Circle",
  status: "active",
  startDate: "2026-06-24",
  durationWeeks: 6,
  targetSize: 8,
  officeCity: "New York",
  members: demoUsers.slice(0, 8),
  score: 88,
  explanation: [
    "8 employees share Wednesday or lunch availability.",
    "The circle mixes Product, Engineering, People, Design, Data, and Finance.",
    "New hire onboarding and cross-functional connection are the dominant goals.",
    "Most employees are hybrid or office-adjacent around the NYC hub.",
  ],
};

export const demoEvents: Event[] = [
  {
    id: "event-1",
    circleId: "circle-1",
    organizationId: "company-nova",
    title: "Cross-Team Lunch Circle",
    description: "A hosted lunch for employees who share hybrid anchor days and want stronger cross-team context.",
    location: "NovaWorks NYC, 8th floor lounge",
    eventType: "lunch",
    officeCity: "New York",
    status: "scheduled",
    startTime: "2026-06-24T12:30:00",
    endTime: "2026-06-24T13:30:00",
  },
  {
    id: "event-2",
    circleId: "circle-1",
    organizationId: "company-nova",
    title: "Walk-and-Talk Reset",
    description: "A short nearby walk with guided prompts for hybrid employees returning to the office.",
    location: "Meet in the NovaWorks lobby",
    eventType: "walk_and_talk",
    officeCity: "New York",
    status: "scheduled",
    startTime: "2026-07-01T16:00:00",
    endTime: "2026-07-01T17:00:00",
  },
];

export const interestOptions = [
  "coffee",
  "lunch",
  "walking",
  "running",
  "books",
  "design",
  "mentorship",
  "career growth",
  "wellness",
  "language exchange",
  "music",
  "strategy",
  "architecture",
  "culture",
  "food",
  "fitness",
  "ERG programming",
  "office exploration",
];
